### PR TITLE
Don't add sources for subproject

### PR DESCRIPTION
**Pull request by TheLartians**
This prevents adding the frozen headers as source files to all libraries that link to the frozen interface library. Otherwise IDEs such as Xcode display the frozen headers as source files for each library that requires frozen.

### CODE REVIEW

**Comment by TheLartians** [comment]
Also this silences a CMake warning when adding frozen as a subdirectory in CMake 3.14:
```
CMake Warning (dev) at build/_deps/frozen-src/include/frozen/CMakeLists.txt:1 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "frozen" has a relative path.
```

**Comment by serge-sans-paille** [comment]
@apmccartney any thoughts on this?

**Comment by TheLartians** [comment]
Just FYI, the way I usually deal with this problem is to create a non-interface target `project-headers` that contains only the headers while the main interface target only has include paths. That way CMake still knows which project the headers belong to (also useful for working in IDEs) while other libraries linking to the interface stay clean.

```CMake
# ---- Header target ----

FILE(GLOB headers "${CMAKE_CURRENT_SOURCE_DIR}/include/*.h")
add_library(EasyIterator-headers EXCLUDE_FROM_ALL ${headers})
SET_TARGET_PROPERTIES(EasyIterator-headers PROPERTIES LINKER_LANGUAGE CXX)

# ---- Create library ----

add_library(EasyIterator INTERFACE)

target_include_directories(EasyIterator
  INTERFACE 
    $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
    $<INSTALL_INTERFACE:include>
)
```

Depending on how you use your library during development, a similar approach might make sense for frozen as well.

**Comment by apmccartney** [comment]
Hello @TheLartians!

> Otherwise IDEs such as Xcode display the frozen headers as source files for each library that requires frozen.

This was intended, but perhaps others don't find this behavior desirable.

> Also this silences a CMake warning when adding frozen as a subdirectory in CMake 3.14

This is due to a recent policy change in CMake. Rather than setting the policy flag, I'd prefer to address the warning.

I have been procrastinating submitting a fix; I apologize if the warning interrupted your work flow. Would you mind if I filed a PR into your fork this weekend to resolve this issue?

> Just FYI, the way I usually deal with this problem is to create a ...

That seems like a reasonable compromise so long as the headers target is exported and installed. (although I consider the globbing [to be a smell](https://youtu.be/bsXLMQ6WgIk)). I can include such a change in the PR (if welcome).

**Comment by TheLartians** [comment]
> This is due to a recent policy change in CMake. Rather than setting the policy flag, I'd prefer to address the warning.
> I have been procrastinating submitting a fix; I apologize if the warning interrupted your work flow. Would you mind if I filed a PR into your fork this weekend to resolve this issue?

Sure, thats a much better solution then my quick fix. I believe I've even enabled write access to frozen maintainers, so if you want just go ahead and edit my branch directly.

Just FYI, the way I like to use dependencies is to [download and add the sources at configure time](https://github.com/TheLartians/CPM) as this guarantees reproducible builds. For this its very convenient when subprojects just silently add their targets and they don't interfere with others. Of course everybody's workflow is different I guess.

> (although I consider the globbing to be a smell).

Oh yeah I forgot about that when pasting the example. Thats just my personal laziness, as I tend to copy-paste my CMake configurations (it even makes no sense here as `EasyIterator` is a single header). As long as you understand the consequences there's nothing wrong with glob though imo.

BTW thanks for this awesome library!

**Comment by apmccartney** [comment]
Hey @serge-sans-paille 

I've [merged work](https://github.com/TheLartians/frozen/pull/1) into @TheLartians pull request branch. Beyond what was requested, I've made a few minor improvements to the CMake. There were a handful of assumptions about the packaging which are true for recent versions of CMake, but not valid for the minimum required version specified. These oversights have been corrected.

I've also modified the travis-CI [yaml](https://github.com/serge-sans-paille/frozen/pull/73/files#diff-354f30a63fb0907d4ad57269548329e3) file such that test coverage will be collected and reported to a public [CDash server](https://my.cdash.org/index.php). I've taken the liberty of establishing a [frozen project page](https://my.cdash.org/index.php?project=frozen), such that each test Travis runs should report there.

That said, for some reason the travis test doesn't seem to be kicking off automatically.

**Comment by apmccartney** [comment]
Success!

https://my.cdash.org/index.php?project=frozen

**Comment by serge-sans-paille** [comment]
LGTM, please just squash the commits

**Comment by serge-sans-paille** [comment]
@apmccartney how did you connect this project to cdash?

**Comment by apmccartney** [comment]
@TheLartians, do you need help squashing the commits?

**Comment by TheLartians** [comment]
Oh I didn't realise that was meant for me (I thought it was referring Github's "squash and merge" feature). 😅 
Sorry, I'll get right to it.

**Comment by serge-sans-paille** [comment]
Thanks to both of you, @TheLartians and @apmccartney

**Pull request merged**
