### PR TITLE
Feature/boyer moore

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Hi @jaydee-io, as you suggested, a text book implementation of Boyer Moore string search!

**Comment by serge-sans-paille** [comment]
@jaydee-io If you're ok with this PR i'll merge it tomorrow!

**Comment by jaydee-io** [comment]
@serge-sans-paille I’m a little busy just now. But if you can wait, I will have some spare time next week and I’ll give a look.

**Comment by serge-sans-paille** [comment]
ok!

**Comment by jaydee-io** [comment]
So everything seems OK for me.
I just made some cosmetic changes for readability (Available on my own feature/boyer-moore branch jaydee-io/frozen@eef202e85f8a5302d2e10d8c4b03cea178b60103).
I also improved the `frozen::string` to be implicitly converted from `const char[N]` (Also available on my own feature/boyer-moore branch jaydee-io/frozen@643c8816f8cd3e655dcdef70d5cf1aa16b3136be).
This enables a more user friendly interface and make the literal operator more or less useless (See example in README.rst).

Also, I think it would be worth to separate 'fonctional' tests cases from 'performance' ones.
So it's possible to just run functionnal tests cases without waiting too long.
And for the performance tests, fully using Google Benchmark to have a lot of different measures and really see the gain of the frozen version respect to the normal one.

**Comment by serge-sans-paille** [comment]
Thanks @jaydee-io! The ``const char (&)[N]`` constructor is a great step forward!
i just fixed a few details in 4f28503fc6744062cb00d877714ae4024ba71d82.
And I agree with test stuff, have to setup this!

**Comment by jaydee-io** [comment]
Great !

Also, I think `frozen/string.h` contains lot of  not-usefull `constexpr` methods.
Whereas, on the other hand, with little effort, some free functions could be made `constexpr` (like `search`).

And you still haven't told me why you added string search algorithm to the frozen library ;-)
For now I can't see the relation to the frozen containers.

**Comment by serge-sans-paille** [comment]
> And you still haven't told me why you added string search algorithm to the frozen library ;-)
I realized that frozen was going to be a collection of algorithms and data structures that have a non-trivial initialization step that can be done at compile-time, making them a valubale alternative to their run-time counterpart.

**Comment by jaydee-io** [comment]
> I realized that frozen was going to be a collection of algorithms and data structures that have a non-trivial initialization step that can be done at compile-time, making them a valubale alternative to their run-time counterpart.

Ok, I better understand now. I agree with you and think this is a good goal for Frozen.

**Pull request merged**
