### PR TITLE
Throw exception upon inconsistent initialization

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@cbeck88 do you think there's a better way than throwing to do that check?

**Comment by cbeck88** [comment]
If I were you, I would deprecate and eventually remove the `std::initializer_list` ctor. IMO they are a poorly designed language feature and should never be used. That's my 2 cents anyways.

Throwing an exception is not ideal because some people may be compiling with `-fno-exceptions` for embedded devices. Lots of those ppl would be very interested in constexpr maps for configuration data etc., for many of the reasons that tesla is.

A nice compromise if we must have exceptions is, add a configuration macro `FROZEN_NO_EXCEPTIONS` that can be used to turn off all try catch throw and make frozen compile with `-fnoexceptions`. This would be similar to `BOOST_NO_EXCEPTIONS`, except better because frozen doesnt actually have any throwing api calls.

**Comment by smkanadl** [comment]
Probably you can go for something like this.
```
template<typename ValueType, size_t N>
class map
{
public:

    map(const ValueType(&keys)[N])
    {
    }
};

auto map = map<int, 8>({ 1, 2, 3, 4, 5, 6, 7, 8 });
```

It can still use list-initialisation and gives a compiler error if N and number of list elements do not match. I used this once on a map-like implementation where I needed a constructor for key and value arrays with the same size.

**Comment by cbeck88** [comment]
@smkanadl yeah IMO that's perfect, together with the `frozen::make_map` thing. Why even wander into the `std::initializer_list` tarpit at all

**Comment by serge-sans-paille** [comment]
Initializer list is important because it makes ``frozen::map`` a straight subsitute so ``std::map``. Irecogn the ``-fno-exception`` argument, working on it :-)

**Comment by smkanadl** [comment]
Ok, having an std-compatible interface is a valuable argument. Then we have to wait for constexpr support in `std::initializer_list` probably coming in `c++22` or something like that. :-)

**Comment by cbeck88** [comment]
> Initializer list is important because it makes frozen::map a straight subsitute so std::map

I don't really get this argument: `frozen::map` is pretty different from `std::map`, and it's not at all a drop-in replacement:

- At the least, `frozen::map` requires an extra template parameter for the size, so you are going to have to modify any declaration of `frozen::map`. If people have to modify the declarations like this, and it can't be done with sed, or in an automated way, then why not also ask them to fixup the braces if they were using initializer lists? Or use the `auto = make_map` syntax?
- `frozen::map` cannot be changed after initialization, while `std::map` can, so it can't be substituted blindly in any such place. It's a different type with different meaning and different interface already.
- Using `std::initializer_list` means that we take something that should be a compile-time failure, and turn it into a run-time failure, which is always bad. A lot of modern c++ techniques are about trying to turn run-time failures into compile-time failures.

The only compelling reason I can see to support `std::initializer_list` is for backwards compatibility with ourselves -- that's why I would suggest deprecating it.

**Comment by serge-sans-paille** [comment]
@cbeck88 : I'm not sure if that argument will touch you, but I used the intiializer list to add something like that:

```cpp
#if __cplusplus < 201402
#define frozen_map(K, V, N) const std::map<K, V>
#else
#define frozen_map(K, V, N) constexpr frozen::map<K, V, N>
#endif
```

but that's probably not a good argument :-)

**Comment by cbeck88** [comment]
Ok I admit, I didn't see your `frozen_map` macro coming... :)

I guess if you've already found this ctor useful to you, I can't much argue with that.

Here's an SO post on, why can't I `static_assert` about the size of `initializer_list`: https://stackoverflow.com/questions/5438671/static-assert-on-initializer-listsize

If you want to keep the initializer list ctor it's not that big a deal in the end. But if I were making the library from scratch I probably would argue against it more strongly. And I think in the version of frozen that is in tesla code base I deleted it, because we generally aren't supposed to use exceptions, and we didn't want to have the problems of size mismatches sneak by silently.

**Comment by serge-sans-paille** [comment]
>  because we generally aren't supposed to use exceptions

There are a bunch of throw in the frozen code. Are you just ``std::abort``ing ?

**Comment by cbeck88** [comment]
> There are a bunch of throw in the frozen code. Are you just `std::abort`ing ?

Well we certainly aren't catching them... :)

The parts we are using are `map` and `set` basically, and we'd like to use the `unordered` versions also but we are still on gcc 5. I didn't see any `throw` in any of this when we started.

Looking again, I guess there is one throw for `map::at` ? I see that in our copy of frozen also.

The programmers are going to know they shouldn't use that, but I guess it snuck by review. probably they would have said I should delete it anyways.

I mean basically, it's pointless to have `throw` in a `constexpr` library, because you cannot catch exceptions at compile-time. Any throw aborts the computation. So I don't know why you want to have it -- only for compatibility with `std::` ?

From my point of view, it's possible to implement frozen without exceptions or dynamic allocations, since none of these things are allowed at compile-time anyways. In a lot of embedded applications, there just isn't really support for these features in whatever tiny chip they use. In our case, we could do it, but the policy is we aren't supposed to do it while the car is driving. All the allocations etc. are supposed to be done during an initialization phase, and then we have a hook into malloc that prevents people from making new allocations accidentally once the firmware has initialized.

**Comment by serge-sans-paille** [comment]
> I mean basically, it's pointless to have throw in a constexpr library, because
> you cannot catch exceptions at compile-time. Any throw aborts the computation.
> So I don't know why you want to have it -- only for compatibility with std:: ?

The following use case looks legit to me:

```
int lookup(int key) {
    constexpr frozen::map<int, int> kv{{1,2}, {3,4}};
    return kv.at(key);
}
```

And yes we mimic ``std::map`` behavior in that case.

> From my point of view, it's possible to implement frozen without exceptions or
> dynamic allocations, since none of these things are allowed at compile-time
> anyways. In a lot of embedded applications, there just isn't really support for
> these features in whatever tiny chip they use. In our case, we could do it, but
> the policy is we aren't supposed to do it while the car is driving. All the
> allocations etc. are supposed to be done during an initialization phase, and
> then we have a hook into malloc that prevents people from making new
> allocations accidentally once the firmware has initialized.

Fascinating! Thanks for sharing that. I guess adding a guard
on ``FROZEN_DISABLE_EXCEPTION`` sounds legit? In libstdc++ code, there's
a macro called ``_GLIBCXX_THROW_OR_ABORT`` we could use something
similar.

**Comment by serge-sans-paille** [comment]
@cbeck: added the optional exception handlign we've been talking about, automatically detecting exception support using some compiler magic variables.

**Comment by cbeck88** [comment]
> The following use case looks legit to me: 
>``` 
>    int lookup(int key) { constexpr frozen::map<int, int> kv{{1,2}, {3,4}}; return kv.at(key); }
> ```

The thing is, here's what I can't do:

```
    boost::optional<int> lookup(int key) {
        constexpr frozen::map<int, int> kv{{1,2}, {3, 4}};
        try {
            return kv.at(key);
        } catch (...) {
            return boost::none;
        }
    }
```

This would work as expected at run time, but if the failing case of `kv.at(key)` ever happens as part of a compile-time expression, compilation is terminated -- similar to `std::abort`. Stack unwinding doesn't happen as part of `constexpr`.

Here's a blog post from Eric Niebler about this: http://ericniebler.com/2014/09/27/assert-and-constexpr-in-cxx11/

Actually, his fix #3 is what we are using right now to create "assertions" in `constexpr` functions in production -- because we aren't able to use `assert` in `constexpr` in C++11, we can only use `throw` to signal errors in `constexpr`. But, we aren't allowed to throw exceptions either. So, we throw an exception that calls `std::abort` in its constructor, so that the exception is never actually in flight if it gets thrown at run-time.

This experience is also partly why I suggest getting rid of the initializer lists -- error handling "after the fact" in a `constexpr` constructor is extremely convoluted right now especially if you can't use exceptions at runtime. Once we take the `initializer_list` in the ctor, the cat is somewhat out of the bag.

**Comment by cbeck88** [comment]
> automatically detecting exception support using some compiler magic variables.

In the gcc docu:

> In sum, valid C++ code with exception handling is transformed into a dialect without exception handling. In detailed steps: all use of the C++ keywords try, catch, and throw in the standard library have been permanently replaced with the pre-processor controlled equivalents spelled __try, __catch, and __throw_exception_again. They are defined as follows.
> 
> ```
>    #if __cpp_exceptions
>    # define __try      try
>    # define __catch(X) catch(X)
>    # define __throw_exception_again throw
>    #else
>    # define __try      if (true)
>    # define __catch(X) if (false)
>    # define __throw_exception_again
>    #endif
> ```

I think we could do this, but `__cpp_exceptions` is not a standard language feature, it's a gcc extension. I guess we can try to do it for gcc and clang this way? I don't know if there is `-fno-exceptions` for MSVC, or if there is a feature detection macro for it.

I think for anyone using a non-standard compiler, like intel or nvcc, or whatever, they would rather want to have a configuration define they can manually change like `BOOST_NO_EXCEPTIONS` -- I think that's the most portable route. If you want to try to make that define "smart", like, it tries to default to an intelligent value by inspecting `__cpp_exceptions`, but the user has the option to set it manually and that will override the setting -- i.e. we do like `#ifndef FROZEN_NO_EXCEPTIONS` and then define try to define it to zero or one by inspecting these symbols to make our best guess, that's probably the friendliest and most portable way to do it, IMO

**Comment by serge-sans-paille** [comment]
I've implemented the ``FROZEN_NO_EXCEPTIONS`` stuff that totally makes sense for other compilers.

I totally understand your point about ``std::initializer_list``. So instead of finding a convoluted way to badly handle all cases *in fine*, I'll stick with current version that just does the job at constexpr time.

**Comment by cbeck88** [comment]
Thanks!

**Pull request merged**
