### PR TITLE
CMake + CDash

### PR DESCRIPTION
**Pull request by apmccartney**
Following up on the pull request from @TheLartians

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
ok, it's here :-)

**Comment by serge-sans-paille** [comment]
I'm surprised ``ctest -VV -M Experimental -T Submit`` is enough!

**Comment by apmccartney** [comment]
> I'm surprised ctest -VV -M Experimental -T Submit is enough!

Note that Frozen would now be running the tests in a so-called Dashboard mode, and the tests are configured with some additional information (`DROP_*`), but you're right; it's a light lift to take advantage of CDash. 

You might have noticed the `CTestCustom.cmake` file. Right now, this is just being used to exclude the test files and system headers from the coverage report. This file supports a number of CTest [customizations](https://gitlab.kitware.com/cmake/community/wikis/doc/ctest/Testing-With-CTest#customizing-ctest) that might prove useful in the future.

Did you notice the [coverage reports](https://my.cdash.org/viewCoverage.php?buildid=1655800&status=6&dir=include/frozen)? Unfortunately, gcov cannot identify untested code in an uninstantiated function template and/or method of a class/struct template, so be a little skeptical of the total coverage percentage figure. That said, the line-by-line reports for each file are sufficient to identify untested methods or branches.

> failing test

It appears that gcov ran out of memory on the VM while collecting coverage information on one of the builds. I'm not sure what we can do to prevent that.

If you're happy with the pr, I'll wait for the other PR to resolve, rebase, and squash

**Comment by apmccartney** [comment]
@serge-sans-paille While I'm messing with things, would you like me to change the `CPACK_PACKAGE_VENDOR` to something other than quarkslab?

**Comment by apmccartney** [comment]
> It appears that gcov ran out of memory on the VM while collecting coverage information on one of the builds. I'm not sure what we can do to prevent that.

Resolved =)

**Comment by apmccartney** [comment]
ping @serge-sans-paille

**Comment by serge-sans-paille** [comment]
I trust you on this one :-)

**Pull request merged**
