### PR TITLE
Added basic CPack support

### PR DESCRIPTION
**Pull request by apmccartney**
Greeting again. This pull request extends the cmake support a bit and adds some inline comments explaining what is being done.

p.s. congrats on your CPPCon acceptance!

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Here and back again :-)

Thanks for the patch, I need to investigate why travis does not like your change :-)

**Comment by apmccartney** [comment]
Oh, I need to add a flag back to the examples. Sorry, I should have noted this was a work in progress.

**Comment by apmccartney** [comment]
The tests are now compiled with relatively strict warning flags with warnings treated as errors. This treatment is conservative, but given frozen is header-only, probably prudent. Failing to do so would prevent, or at least obstruct, composing projects from doing so.

This revealed at least one actual bug. See #52 for more information, This issue seems somewhat fundamental, so I defer to you regarding an appropriate solution.

On MSVC, there appear to be some (probably benign) narrowing conversion warnings, but several warnings indicate integral constant overflow, which might warrant some investigation.

**Comment by serge-sans-paille** [comment]
@apmccartney now that some warning have been fixed by #53, can you rebase your patches on master?

**Comment by apmccartney** [comment]
Wow you work fast! I'll rebase this evening and uncomment the test in question.

**Comment by serge-sans-paille** [comment]
ok, all the windows warning remain, I'll try to fix that!

**Comment by serge-sans-paille** [comment]
#54 adds the warning fix

**Comment by serge-sans-paille** [comment]
Obsoleted by #54

**Pull request closed without merging**
