### PR TITLE
gcc 8 unused variable warning

### PR DESCRIPTION
**Pull request by divaykin**
fix GCC 8 compilation warnings

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Unfortunately, this is a C++17 feature and frozen supports c++14. You could write a compatibility macro though, relyin on __attribute__((unused)) for gcc and clang, don't known the MSVC alterantive on top of my head.

**Comment by cbeck88** [comment]
FWIW the way I would prefer to fix this is to put a line at the end of the function:

```
static_cast<void>(olaf0);
static_cast<void>(olaf1);
```

this suppresses such errors in gcc and clang, and is portable to boot

**Comment by serge-sans-paille** [comment]
Cool, thanks!

**Comment by serge-sans-paille** [comment]
@cbeck88 thanks for the tip!

**Pull request closed without merging**
